language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t rnwokoye/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true rnwokoye/docker-react npm run test
  # - docker run rnwokoye/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "aws-logs-633226805238-us-east-2"
  bucket_path: "docker-react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    #secure: "$AWS_SECRET_KEY"
